config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :questions do
    resources :comments, only: [:new, :create]
    resources :answers do
      resources :comments, only: [:new, :create]
    end
  end

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  root 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable

  validates_presence_of :title, :body
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable

  validates_presence_of :title, :body
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  has_many :comments

  validates_presence_of :email, :username
  validates_uniqueness_of :email, :username

  has_secure_password
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find_by(id: params[:question_id])
    @answer = @question.answers.build(answer_params)
    @answer.user_id = current_user.id

    if @answer.save
      redirect_to @question
    else
      render 'questions/show'
    end
  end

  def show
    @answer = Answer.find_by(id: params[:id])
  end

  private
    def answer_params
      params.require(:answer).permit(:title, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to new_session_path unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

   def create
    if params[:answer_id]
        @commentable = Answer.find(params[:answer_id])
    else
        @commentable = Question.find(params[:question_id])
    end

    @comment = @commentable.comments.build(comment_params)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.update_attributes(:user_id => current_user.id)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def show
    @question = Question.find_by(id: params[:id])
  end

  private
    def question_params
      params.require(:question).permit(:title, :body)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment] do |f| %>

  <% if @comment.errors.any? %>
    <div id="error-explanation">
      <h2>
        <%= pluralize(@comment.errors.count, "error")%>  prohibited this question from being saved:
      </h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Home', questions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsOverflowChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      Signed in as <%= current_user.username %> | <%= link_to "Logout", session_path(current_user), method: :delete %>
    <% else %>
      <%= link_to 'Login', new_session_path %> | <%= link_to 'Signup', new_user_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for :question, url: questions_path do |f| %>

  <% if @question.errors.any? %>
    <div id="error-explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error")%>  prohibited this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/index.html.erb
<h1>Questions: </h1>

<% if session[:user_id] %>
  <%= link_to 'Add a new question', new_question_path %>
<% end %>

<% @questions.each do |question| %>
<h2><%= question.title %></h2>
<p><%= question.body %></p>
<td><%= link_to 'Show', question_path(question) %></td>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Home', questions_path %>

app/views/questions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @question.body %>
</p>

<p>
<%= link_to 'Add a Comment', new_question_comment_path(@question) %>
</p>

<strong>Add an Answer:</strong>
<%= form_for([@question, @question.answers.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<% @question.answers.each do |ans| %>
<p>
  <% if ans.persisted? %>
    <%= ans.title %><br>
    <%= ans.body %>
    <%= link_to 'Add a Comment', new_question_answer_comment_path(ans) %>
  <% end %>
</p>
<% end %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: users_path do |f| %>

  <% if @user.errors.any? %>
    <div id="error-explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error")%>  prohibited this article from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  Username: <%= f.text_field :username %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>